INSERT INTO SPRINGSPROUT(NAME, NICKNAME) VALUES('아롱', 'Arawn');
INSERT INTO SPRINGSPROUT(NAME, NICKNAME) VALUES('아대장', 'Outsider');
INSERT INTO SPRINGSPROUT(NAME, NICKNAME) VALUES('제이드', 'Zeide');

INSERT INTO LANGUAGE(NAME) VALUES('Java');
INSERT INTO LANGUAGE(NAME) VALUES('Scala');
INSERT INTO LANGUAGE(NAME) VALUES('JavaScript');
INSERT INTO LANGUAGE(NAME) VALUES('Objective C');

--INSERT INTO SPRINGSPROUT_LANGUAGE(0, 2);
--INSERT INTO SPRINGSPROUT_LANGUAGE(0, 3);
--
--INSERT INTO SPRINGSPROUT_LANGUAGE(1, 1);
--INSERT INTO SPRINGSPROUT_LANGUAGE(1, 2);
--
--INSERT INTO SPRINGSPROUT_LANGUAGE(2, 0);
--INSERT INTO SPRINGSPROUT_LANGUAGE(2, 1);
--INSERT INTO SPRINGSPROUT_LANGUAGE(2, 2);